services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - mysqlsockdir:/var/run/mysqld
    configs:
      - source: init_sql
        target: /docker-entrypoint-initdb.d/init-mysql-docker-compose.sql
      - source: mysql_cnf
        target: /etc/mysql/conf.d/docker-mysql.cnf
    network_mode: none
  rails:
    build: .
    volumes:
      - mysqlsockdir:/var/run/mysqld
    ports:
      - "3000:3000"
    network_mode: bridge
    depends_on:
      - mysql
volumes:
  mysqlsockdir:
