export const CHANGE_TEXT = "CHANGE_TEXT";
export const CHANGE_TAB = "CHANGE_TAB";
export const ONCLICK_EDIT = "ONCLICK_EDIT";
export const ONCLICK_CANCEL = "ONCLICK_CANCEL";
export const SET_CONTENT = "SET_CONTENT";
export const CHANGE_READABLE_GROUP = "CHANGE_READABLE_GROUP";
export const CHANGE_EDITABLE_GROUP = "CHANGE_EDITABLE_GROUP";
